---
title: "Homework 6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#DATA CLEANING

library(tidyverse)
install.packages("devtools")
devtools::install_github("hadley/productplots")
data(happy, package="productplots")

head(happy)
HAPPY <- readRDS("data/HAPPY.rds")
head(HAPPY)

HAPPY[HAPPY == "IAP"] <- "NA"
HAPPY[HAPPY == "DK"] <- "NA"
head(HAPPY)

str(HAPPY)
HAPPY[HAPPY == "89 OR OLDER"] <- "89"
class(HAPPY$AGE) = "numeric"
str(HAPPY)

str(HAPPY)
HAPPY$HAPPY = as.factor(HAPPY$HAPPY)
HAPPY$SEX = as.factor(HAPPY$SEX)
HAPPY$MARITAL = as.factor(HAPPY$MARITAL)
HAPPY$DEGREE = as.factor(HAPPY$DEGREE)
HAPPY$FINRELA = as.factor(HAPPY$FINRELA)
HAPPY$HEALTH = as.factor(HAPPY$HEALTH)
HAPPY$PARTYID = as.factor(HAPPY$PARTYID)
levels(HAPPY$HAPPY)
levels(HAPPY$SEX)
levels(HAPPY$MARITAL)
mean(filter(HAPPY, MARITAL == "DIVORCED")$AGE, na.rm=TRUE)
mean(filter(HAPPY, MARITAL == "MARRIED")$AGE, na.rm=TRUE)
mean(filter(HAPPY, MARITAL == "NEVER MARRIED")$AGE, na.rm=TRUE)
mean(filter(HAPPY, MARITAL == "SEPARATED")$AGE, na.rm=TRUE)
mean(filter(HAPPY, MARITAL == "WIDOWED")$AGE, na.rm=TRUE)
levels(HAPPY$MARITAL) = c("NEVER MARRIED", "SERPARATED", "MARRIED", "DIVORCED", "WIDOWED")
levels(HAPPY$MARITAL)
levels(HAPPY$DEGREE)
levels(HAPPY$DEGREE) = c("NA", "LT HIGH SCHOOL", "HIGH SCHOOL", "JUNIOR COLLEGE", "BACHELOR", "GRADUATE")
levels(HAPPY$DEGREE)
levels(HAPPY$FINRELA)
levels(HAPPY$FINRELA) = c("NA", "FAR BELOW AVERAGE", "BELOW AVERAGE", "AVERAGE", "ABOVE AVERAGE", "FAR ABOVE AVERAGE")
levels(HAPPY$FINRELA)
levels(HAPPY$HEALTH)
levels(HAPPY$HEALTH) = c("NA", "POOR", "FAIR", "GOOD", "EXCELLENT")
levels(HAPPY$HEALTH)
levels(HAPPY$PARTYID)
##Decided to order these as best I could from left to right so from strong Democrat to strong Republican, but leaving it alone was definitely an option since no affiliation is better than the other
levels(HAPPY$PARTYID) = c("NA", "STRONG DEMOCRAT", "NOT STR DEMOCRAT", "IND, NEAR DEM", "INDEPENDENT", "OTHER PARTY", "IND, NEAR REP", "NOT STR REPUBLICAN", "STRONG REPUBLICAN")
levels(HAPPY$PARTYID)

#HAPPINESS INVESTIGATION

ggplot(HAPPY, aes(x=HAPPY)) + geom_bar() + scale_x_discrete(labels = c("-", "0", "+", "N")) + facet_grid(rows = vars(SEX), cols = vars(HEALTH))
##I chose to look at the physical aspects that could affect happiness: sex and health. Looking oat the bar graphs, there just isn't much of a correlation. There seem to be less Male responses, but the distribution of the graphs between Male and Female look very similar. There does seem to be a little bit of a correlation between health and happiness, however. The graphs of poor health look like the very happy bar is around 1/3 the size of the pretty happy bar while those with fair health look like their very happy bar is closer to 1/2 of the pretty happy bar. Then, the good health graph looks like it might have a very happy bar that is a little bit over 1/2 if the pretty happy bar. The excellent health graph has too small of a pool to really draw any accurate conclusions.

